services:
  - type: web
    name: portel-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    branch: master
    envVars:
      - key: PORT
        value: 10000
